# Generated by Django 3.2.3 on 2021-06-07 12:11

from django.db import migrations, models
import stuff.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='نام و نام خانوداگی')),
                ('image', models.ImageField(blank=True, null=True, upload_to=stuff.models.upload_image_path, verbose_name='تصویر')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیخات')),
                ('phone', models.IntegerField(verbose_name='شماره تلفن')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
            ],
            options={
                'verbose_name': 'stuff',
                'verbose_name_plural': 'Stuff',
            },
        ),
    ]
