# Generated by Django 3.2.3 on 2021-06-07 12:11

from django.db import migrations, models
import django.db.models.deletion
import homes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stuff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='آپشن ها')),
            ],
            options={
                'verbose_name': 'amenities',
                'verbose_name_plural': 'Amenities',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='شهر')),
            ],
            options={
                'verbose_name': 'city',
                'verbose_name_plural': 'City',
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='نام ساختمان')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('area', models.IntegerField(verbose_name='متراژ')),
                ('bedroom', models.IntegerField(verbose_name='تعداد اتاق خواب')),
                ('baths', models.IntegerField(verbose_name='تعداد سرویس / حمام')),
                ('image', models.ImageField(blank=True, null=True, upload_to=homes.models.upload_image_path, verbose_name='تصویر')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیخات')),
                ('location', models.CharField(max_length=250, verbose_name='آدرس')),
                ('status', models.CharField(max_length=100, verbose_name='وضیعت')),
                ('garage', models.IntegerField(verbose_name='تعداد گاراژ')),
                ('amenities', models.ManyToManyField(related_name='amenities', to='homes.Amenities', verbose_name='آپشن ها')),
                ('city', models.ForeignKey(default=None, max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='city', to='homes.city', verbose_name='شهر')),
            ],
            options={
                'verbose_name': 'home',
                'verbose_name_plural': 'HOMES',
            },
        ),
        migrations.CreateModel(
            name='HomeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='نوع ساختمان')),
            ],
            options={
                'verbose_name_plural': 'HomeType',
            },
        ),
        migrations.CreateModel(
            name='HomeGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='نام عکس')),
                ('image', models.ImageField(blank=True, null=True, upload_to=homes.models.upload_gallery_image_path, verbose_name='تصویر')),
                ('home', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='homes.home', verbose_name='ساختمان')),
            ],
            options={
                'verbose_name': 'gallery',
                'verbose_name_plural': 'Gallery',
            },
        ),
        migrations.AddField(
            model_name='home',
            name='home_type',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='homes.hometype', verbose_name='نوع ساختمان'),
        ),
        migrations.AddField(
            model_name='home',
            name='stuff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stuff', to='stuff.stuff', verbose_name='مشاور'),
        ),
    ]
