# Generated by Django 3.2.3 on 2021-07-14 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0001_initial'),
        ('homes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('text', models.TextField()),
                ('stuff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stuff.stuff')),
            ],
        ),
    ]
