# Generated by Django 3.2.3 on 2021-07-14 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0001_initial'),
        ('homes', '0002_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='stuff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_stuff', to='stuff.stuff'),
        ),
    ]
