# Generated by Django 3.2.3 on 2021-07-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0003_alter_message_stuff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='status',
            field=models.CharField(choices=[('Sale', 'sale'), ('Mortgage', 'mortgage'), ('Rent', 'rent'), ('Mortgage And Rent', 'mortgage and rent')], max_length=100, verbose_name='وضیعت'),
        ),
    ]
