# Generated by Django 3.2.3 on 2021-07-14 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0004_alter_home_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='price',
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_sale', models.IntegerField(blank=True, null=True)),
                ('price_mortgage', models.IntegerField(blank=True, null=True)),
                ('price_rent', models.IntegerField(blank=True, null=True)),
                ('price_mortgage_and_rent', models.IntegerField(blank=True, null=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr', to='homes.home')),
            ],
        ),
    ]
