# Generated by Django 3.2.3 on 2021-07-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0005_auto_20210714_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='price_mortgage_and_rent',
        ),
        migrations.AlterField(
            model_name='home',
            name='status',
            field=models.CharField(choices=[('Sale', 'sale'), ('Mortgage', 'mortgage'), ('Rent', 'rent')], max_length=100, verbose_name='وضیعت'),
        ),
    ]
